name: av
channels:
 - pytorch
 - nvidia
dependencies:
 - python=3.11.7
 - pip=23.3.1
 - pytorch=2.1.2
 - torchvision=0.16.2
 - torchaudio=2.1.2
 - pytorch-cuda=12.1
 - pip:
    # Mainland China users please use the pip mirror,
    # and uncomment these three lines. Then comment out the
    # github links on line 32.
    #  - -i https://pypi.tuna.tsinghua.edu.cn/simple
    #  - pypesq==1.2.4
    #  - sru==2.6.0
     - opencv-python==4.9.0.80
     - soundfile==0.12.1
     - scipy==1.12.0
     - pystoi==0.4.1
     - thop==0.1.1.post2209072238
     - timm==0.9.12
     - pytorch-lightning==2.1.3
     - torch-optimizer==0.3.0
     - tensorboard==2.15.1
     - black==24.1.0
     - pandas==2.2.0
     - sigfig==1.3.3
     - einops==0.7.0
     - git+https://github.com/vBaiCai/python-pesq.git