name: av
channels:
 - pytorch
 - nvidia
dependencies:
 - pip=23.2.1
 - pytorch=2.0.0
 - torchvision=0.15.0 
 - torchaudio=2.0.0 
 - pytorch-cuda=11.8
 - pip:
    #  - -i https://pypi.tuna.tsinghua.edu.cn/simple
     - opencv-python==4.7.0.72 
     - soundfile==0.12.1
     - scipy==1.10.1
     - pystoi==0.3.3
     - thop==0.1.1.post2209072238
     - timm==0.6.13
     - pytorch-lightning==2.0.2
     - torch-optimizer==0.3.0 
     - tensorboard==2.13.0
     - black==23.3.0
     - pandas==2.0.1
     - sigfig==1.3.2
     - einops==0.6.1
     - pypesq==1.2.4